[package]
name = "gpak2c"
version = "0.1.0"
authors = ["Egor Markov <emarkov@notanotherone.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.12"
